### ISSUE TITLE
Detailed SHR results

### ISSUE THREAD

**Issue by pritamqu** [opendatalab/HA-DPO#3]
Hello, 

I am trying SHR evaluation and would like to compare the results, could you please share the following:

- average generation length (i.e., words_per_image, sents_per_image) of the reported numbers, e.g., in Table 3; 
- Or it would be even better if you could share the full metrics.json file for the corresponding models. As you understand, getting a lower SHR is easy if the generated length is very small.
- also, I guess the SHR reported in Table 3 is the same as mean_hal_ratio*100 in the metrics.json file?

Thanks!

**Comment by JulioZhao97** [comment]
Thanks for your interest in our work! Here are the full metrics:
### MiniGPT4
| HA-DPO | metric file |
| :--:  | :--:  |
| n | [metrics.json](https://github.com/opendatalab/HA-DPO/files/14644072/metrics.json) |
| y | [metrics.json](https://github.com/opendatalab/HA-DPO/files/14644078/metrics.json) | 
### InstructBLIP
| HA-DPO | metric file |
| :--:  | :--: |
| n | [metrics.json](https://github.com/opendatalab/HA-DPO/files/14644100/metrics.json) |
| y | [metrics.json](https://github.com/opendatalab/HA-DPO/files/14644110/metrics.json) |
### LLaVA-1.5
| HA-DPO | metric file |
| :--:  | :--: |
| n | [metrics.json](https://github.com/opendatalab/HA-DPO/files/14644125/metrics.json) |
| y | [metrics.json](https://github.com/opendatalab/HA-DPO/files/14644137/metrics.json) |

As far as our concern:
1. It is indeed that SHR is lower when the model is very cautious (output few words or sentences), so we use ```average generation length``` to indicate whether this phenomenon happens. And HA-DPO won't lead to a decrease in generation length.
2. Yes, the SHR in Table3 is the same as mean_hal_ratio*100 in the metrics.json file, which is the average number of hallucinated sentences.

**Comment by pritamqu** [comment]
awesome! appreciate it.
