### ISSUE TITLE
Only minigpt4 use λLaux loss?

### ISSUE THREAD

**Issue by crazy-wq** [opendatalab/HA-DPO#5]
Only minigpt4 use λLaux loss in the source code?

**Comment by JulioZhao97** [comment]
Yes. In our experiment, we found that the MiniGPT4, even after fine-tuning with style-consistent data, still exhibits a degree of degeneracy. Therefore, we introduced auxiliary task to further alleviate this degeneration phenomenon. For more powerful models, such as LLaVA and InstructBLIP, the preference fine-tuning does not affect the generation of the model, so auxiliary tasks were not employed. Details can be found in Sec5.2 in paper, where λ is set to 0 for LLaVA and InstructBLIP.
