### ISSUE TITLE
Question about the code.

### ISSUE THREAD

**Issue by tbbbk** [opendatalab/HA-DPO#6]
[Here](https://github.com/opendatalab/HA-DPO/blob/42f72c536984c6ded016e89b70266f29f2428f33/ha_dpo/models/llava-v1_5/train_dpo.py#L218) Why does this variable A need to be multiplied by two here？

Best wishes.

**Comment by tbbbk** [comment]
> [Here](https://github.com/opendatalab/HA-DPO/blob/42f72c536984c6ded016e89b70266f29f2428f33/ha_dpo/models/llava-v1_5/train_dpo.py#L218) Why does this variable A need to be multiplied by two here？
> 
> Best wishes.

Typo: `A` -> `desc_data_dict`

**Comment by JulioZhao97** [comment]
This ratio controls the degree of optimization for the two different types of data, and we found in our experiments that for llava, the model was able to achieve the best hallucination elimination on both image description and question answering when this ratio was controlled at 2:1. You can change other values in the experiment to observe the effect in different cases.

**Comment by tbbbk** [comment]
> This ratio controls the degree of optimization for the two different types of data, and we found in our experiments that for llava, the model was able to achieve the best hallucination elimination on both image description and question answering when this ratio was controlled at 2:1. You can change other values in the experiment to observe the effect in different cases.

I apologize, it may be my oversight. Could you please tell me which part of the paper mentions 'ratio'?

**Comment by JulioZhao97** [comment]
> > This ratio controls the degree of optimization for the two different types of data, and we found in our experiments that for llava, the model was able to achieve the best hallucination elimination on both image description and question answering when this ratio was controlled at 2:1. You can change other values in the experiment to observe the effect in different cases.
> 
> I apologize, it may be my oversight. Could you please tell me which part of the paper mentions 'ratio'?

We didn't elaborate this much in the current version of the paper since this hyper-parameter can be left for the user to decide and doesn't have much influence on the performance. We will add this in the next version of the paper.
