### ISSUE TITLE
Dose the ref_model really need?

### ISSUE THREAD

**Issue by liuxingbin** [opendatalab/HA-DPO#8]
Hi,
Thanks for the great work, I am curious about the red model, Can I set the ref_model to None, as I see here: https://github.com/opendatalab/HA-DPO/blame/main/ha_dpo/trainer/base_dpo_trainer.py#L298. When you set `reference_free=False`, you do not need a ref-model to save computation resources.

**Comment by pspdada** [comment]
You can take a look at https://github.com/opendatalab/HA-DPO/issues/4#issuecomment-2017110154; this might be helpful for your issue.
